### ISSUE TITLE
New action creation fails in rasa interactive

### ISSUE THREAD

**Issue by tayfun** [RasaHQ/rasa#9977]
### Rasa Open Source version

2.8.12

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

A new action creation in `rasa interactive` fails with errors:
```
? What is the next action of the bot? <create new action>                                                                                                                                             
? Please type the action name: utter_uk                                                                                                                                                               
? Please type the message for your new bot response 'utter_uk': London is in the UK.                                                                                                                  
Thanks! The bot will now run utter_uk.

2021-10-25 16:54:44 DEBUG    rasa.core.lock_store  - Issuing ticket for conversation '63f3066b6866454ca6d9f2a1d3abe23b'.
2021-10-25 16:54:44 DEBUG    rasa.core.lock_store  - Acquiring lock for conversation '63f3066b6866454ca6d9f2a1d3abe23b'.
2021-10-25 16:54:44 DEBUG    rasa.core.lock_store  - Acquired lock for conversation '63f3066b6866454ca6d9f2a1d3abe23b'.
2021-10-25 16:54:44 DEBUG    rasa.core.tracker_store  - Recreating tracker for id '63f3066b6866454ca6d9f2a1d3abe23b'
2021-10-25 16:54:44 DEBUG    rasa.core.lock_store  - Deleted lock for conversation '63f3066b6866454ca6d9f2a1d3abe23b'.
2021-10-25 16:54:44 DEBUG    rasa.server  - Traceback (most recent call last):
  File "/Users/tayfun/w/rasa/rasa/shared/core/domain.py", line 932, in index_for_action
    return self.action_names_or_texts.index(action_name)
ValueError: 'utter_uk' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tayfun/w/rasa/rasa/server.py", line 902, in execute_action
    await app.agent.execute_action(
  File "/Users/tayfun/w/rasa/rasa/core/agent.py", line 610, in execute_action
    prediction = PolicyPrediction.for_action_name(
  File "/Users/tayfun/w/rasa/rasa/core/policies/policy.py", line 554, in for_action_name
    probabilities = confidence_scores_for(action_name, confidence, domain)
  File "/Users/tayfun/w/rasa/rasa/core/policies/policy.py", line 619, in confidence_scores_for
    idx = domain.index_for_action(action_name)
  File "/Users/tayfun/w/rasa/rasa/shared/core/domain.py", line 934, in index_for_action
    self.raise_action_not_found_exception(action_name)
  File "/Users/tayfun/w/rasa/rasa/shared/core/domain.py", line 948, in raise_action_not_found_exception
    raise ActionNotFoundException(
rasa.shared.core.domain.ActionNotFoundException: Cannot access action 'utter_uk', as that name is not a registered action for this domain.
```

Subsequently when you exit the interactive shell, you'll find that domain file cannot be exported to yaml file:

```
2021-10-25 16:55:04 ERROR    rasa.core.training.interactive  - An exception occurred while recording messages.
Traceback (most recent call last):
  File "/Users/tayfun/w/rasa/rasa/core/training/interactive.py", line 1516, in record_messages
    await _enter_user_message(conversation_id, endpoint)
  File "/Users/tayfun/w/rasa/rasa/core/training/interactive.py", line 1354, in _enter_user_message
    message = await _ask_questions(question, conversation_id, endpoint, lambda a: not a)
  File "/Users/tayfun/w/rasa/rasa/core/training/interactive.py", line 325, in _ask_questions
    should_retry = await _ask_if_quit(conversation_id, endpoint)
  File "/Users/tayfun/w/rasa/rasa/core/training/interactive.py", line 651, in _ask_if_quit
    await _write_data_to_file(conversation_id, endpoint)
  File "/Users/tayfun/w/rasa/rasa/core/training/interactive.py", line 628, in _write_data_to_file
    _retry_on_error(_write_domain_to_file, domain_path, events, domain)
  File "/Users/tayfun/w/rasa/rasa/core/training/interactive.py", line 605, in _retry_on_error
    return func(export_path, *args, **kwargs)
  File "/Users/tayfun/w/rasa/rasa/core/training/interactive.py", line 959, in _write_domain_to_file
    old_domain.merge(new_domain).persist_clean(domain_path)
  File "/Users/tayfun/w/rasa/rasa/shared/core/domain.py", line 1569, in persist_clean
    as_yaml = self.as_yaml(clean_before_dump=True)
  File "/Users/tayfun/w/rasa/rasa/shared/core/domain.py", line 1594, in as_yaml
    domain_data[KEY_RESPONSES] = self.get_responses_with_multilines(
  File "/Users/tayfun/w/rasa/rasa/shared/core/domain.py", line 1440, in get_responses_with_multilines
    response_text = example.get(KEY_RESPONSES_TEXT, "")
AttributeError: 'str' object has no attribute 'get'
```

**Comment by melindaloubser1** [comment]
This does work on main/3.0.0rc2 for the record, new custom actions and responses  are added. However, there is this misleading log which looks like an error until you read carefully:

```
2021-11-15 21:25:21 ERROR    rasa.server  - An unexpected error occurred. Error: Cannot access action 'utter_help', as that name is not a registered action for this domain. Available actions are: 
         - action_listen
         - action_restart
         - action_session_start
         - action_default_fallback
         - action_deactivate_loop
         - action_revert_fallback_events
         - action_default_ask_affirmation
         - action_default_ask_rephrase
         - action_two_stage_fallback
         - action_unlikely_intent
         - action_back
         - ...
         - action_extract_slots
         - utter_cheer_up
         - utter_did_that_help
         - utter_goodbye
         - utter_greet
         - utter_happy
         - utter_iamabot
? WARNING: You have created a new action: 'utter_help', with matching response: 'i hlep!'. This action will not return its message in this session, but the new response will be saved to your domain file when you exit and save this session. You do not ne
ed to do anything further. Yes    
```

Should I create a separate issue for this or is it part of this one?
