### ISSUE TITLE
Interactive error

### ISSUE THREAD

**Issue by travelmail26** [RasaHQ/rasa#10803]
### Rasa Open Source version

3.04=.4

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

I'm getting an error in Rasa interactive that I can only sometimes recreate. It started when I upgraded to 3.0\. It happens when I try to force the interactive to correct wrong intents or actions. It does not trigger actions.py. In the output below I retracted some sensitive info.

### Command / Request

 _No response_ 

### Relevant log output

<pre>2022-01-30 15:07:46 ERROR rasa.server - An unexpected error occurred. Error: 'NoneType' object has no attribute 'get'
 2022-01-30 15:07:46 ERROR rasa.core.training.interactive - An exception occurred while recording messages.
 Traceback (most recent call last):
 File "/Users/
 /Dropbox/visualstudiostest/selfbot/venv/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 1498, in record_messages
 await _enter_user_message(conversation_id, endpoint)
 File "/Users/ratracted/Dropbox/visualstudiostest/selfbot/venv/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 1341, in _enter_user_message
 await send_message(endpoint, conversation_id, message)
 File "/Users//Dropbox/visualstudiostest/selfbot/venv/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 161, in send_message
 return await endpoint.request(
 File "/Users//Dropbox/visualstudiostest/selfbot/venv/lib/python3.8/site-packages/rasa/utils/endpoints.py", line 173, in request
 raise ClientResponseError(
 rasa.utils.endpoints.ClientResponseError: 500, Internal Server Error, body='b'{"version":"3.0.4","status":"failure","message":"An unexpected error occurred. Error: \'NoneType\' object has no attribute \'get\'","reason":"ConversationError","details":{},"help":null,"code":500}''
 2022-01-30 15:07:46 ERROR asyncio - Task exception was never retrieved
 future: 

 exception=ClientResponseError('500, Internal Server Error, body=\'b\'{"version":"3.0.4","status":"failure","message":"An unexpected error occurred. Error: \\\'NoneType\\\' object has no attribute \\\'get\\\'","reason":"ConversationError","details":{},"help":null,"code":500}\'\'')>
 Traceback (most recent call last):
 File "/Users//Dropbox/visualstudiostest/selfbot/venv/lib/python3.8/site-packages/sanic/signals.py", line 133, in _dispatch
 retval = await maybe_coroutine
 File "/Users//Dropbox/visualstudiostest/selfbot/venv/lib/python3.8/site-packages/sanic/app.py", line 1374, in run_delayed_task
 await prepped
 File "/Users//Dropbox/visualstudiostest/selfbot/venv/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 1594, in run_interactive_io
 await record_messages(
 File "/Users//Dropbox/visualstudiostest/selfbot/venv/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 1498, in record_messages
 await _enter_user_message(conversation_id, endpoint)
 File "/Users//Dropbox/visualstudiostest/selfbot/venv/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 1341, in _enter_user_message
 await send_message(endpoint, conversation_id, message)
 File "/Users//Dropbox/visualstudiostest/selfbot/venv/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 161, in send_message
 return await endpoint.request(
 File "/Users//Dropbox/visualstudiostest/selfbot/venv/lib/python3.8/site-packages/rasa/utils/endpoints.py", line 173, in request
 raise ClientResponseError(
 rasa.utils.endpoints.ClientResponseError: 500, Internal Server Error, body='b'{"version":"3.0.4","status":"failure","message":"An unexpected error occurred. Error: \'NoneType\' object has no attribute \'get\'","reason":"ConversationError","details":{},"help":null,"code":500}''

 </pre>

**Comment by sara-tagger** [comment]
Thanks for the issue, @sebwarnke will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by travelmail26** [comment]
I'm still encountering this issue. Any progress on it or workarounds?

**Comment by ancalita** [comment]
@travelmail26 I've responded in the corresponding Jira ticket [here](https://rasa-open-source.atlassian.net/browse/OSS-576?focusedCommentId=12769) - please share more info for us to be able to reproduce the issue, especially if you're using custom actions and trying to correct the prediction of a custom action.
