### ISSUE TITLE
rasa init doesn't work

### ISSUE THREAD

**Issue by rumeshmadhusanka** [RasaHQ/rasa#9672]
### Rasa Open Source version

2.8.6

### Rasa SDK version

2.8.2

### Rasa X version

None

### Python version

3.8

### What operating system are you using?

Cloud (AWS / GCP / AZURE)

### What happened?

Tries `rasa init` on a newly created GCP instance (Ubuntu 20.04) and tried to train. An error occurred.
My command history:

 ```
    1  sudo apt update
    2  sudo apt install python3-dev python3-pip
    3  python3 -m venv ./venv
    4  pip3 install -U pip
    5  python3 -m venv ./venv
    6  sudo apt install python3.8-venv
    7  python3 -m venv ./venv
    8  source ./venv/bin/activate
    9  pip3 install rasa
   10  mkdir bot
   11  cd bot
   12  rasa --version
   13  rasa init

```

### Command / Request

```shell
rasa init
```

### Relevant log output

```shell
result = loop.run_until_complete(f)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/rumesh_m_s16/venv/lib/python3.8/site-packages/rasa/model_training.py", line 108, in train_async
    return await _train_async_internal(
  File "/home/rumesh_m_s16/venv/lib/python3.8/site-packages/rasa/model_training.py", line 288, in _train_async_internal
    await _do_training(
  File "/home/rumesh_m_s16/venv/lib/python3.8/site-packages/rasa/model_training.py", line 334, in _do_training
    model_path = await _train_nlu_with_validated_data(
  File "/home/rumesh_m_s16/venv/lib/python3.8/site-packages/rasa/model_training.py", line 758, in _train_nlu_with_validated_data
    await rasa.nlu.train.train(
  File "/home/rumesh_m_s16/venv/lib/python3.8/site-packages/rasa/nlu/train.py", line 96, in train
    trainer = Trainer(
  File "/home/rumesh_m_s16/venv/lib/python3.8/site-packages/rasa/nlu/model.py", line 164, in __init__
    components.validate_requirements(cfg.component_names)
  File "/home/rumesh_m_s16/venv/lib/python3.8/site-packages/rasa/nlu/components.py", line 58, in validate_requirements
    from rasa.nlu import registry
  File "/home/rumesh_m_s16/venv/lib/python3.8/site-packages/rasa/nlu/registry.py", line 12, in <module>
    from rasa.nlu.classifiers.diet_classifier import DIETClassifier
  File "/home/rumesh_m_s16/venv/lib/python3.8/site-packages/rasa/nlu/classifiers/diet_classifier.py", line 24, in <module>
    from rasa.utils.tensorflow.models import RasaModel, TransformerRasaModel
  File "/home/rumesh_m_s16/venv/lib/python3.8/site-packages/rasa/utils/tensorflow/models.py", line 47, in <module>
    from rasa.utils.tensorflow.temp_keras_modules import TmpKerasModel
  File "/home/rumesh_m_s16/venv/lib/python3.8/site-packages/rasa/utils/tensorflow/temp_keras_modules.py", line 26, in <module>
    class TmpKerasModel(tf.keras.models.Model):
  File "/home/rumesh_m_s16/venv/lib/python3.8/site-packages/rasa/utils/tensorflow/temp_keras_modules.py", line 37, in TmpKerasModel
    @training.enable_multi_worker
AttributeError: module 'tensorflow.python.keras.engine.training' has no attribute 'enable_multi_worker'
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @kalkbrennerei will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by kalkbrennerei** [comment]
Hey @rumeshmadhusanka thanks for letting us know! 💯 Since we don't support tensorflow `2.6` yet, `pip3 install rasa` should install a lower version of tensorflow. We have a [PR](https://github.com/RasaHQ/rasa/pull/9678) up to fix this!

You can probably also manually install tensorflow `2.3.4` and it should work

**Comment by kalkbrennerei** [comment]
It should work now with rasaos `2.8.7` 🎉
I'm closing this issue

**Comment by rahulvashistha** [comment]
Still facing the same problem.
Can't degrade the tensorflow version and rasa in not working with 2.6.0.

RASA current pacakages.
rasa                          0.1.1
rasa-core                     0.8.6
rasa-nlu                      0.11.5
