### ISSUE TITLE
 module 'aio_pika' has no attribute 'abc' bug in 3.2.6

### ISSUE THREAD

**Issue by vunhatchuong123** [RasaHQ/rasa#11447]
### Rasa Open Source version

3.2.6

### Python version

3.9

### What operating system are you using?

Windows

### What happened?

No matter what rasa command I run, it will output the same error and can't run rasa.

![image](https://user-images.githubusercontent.com/20581504/184432819-e29d1e32-ae6e-4924-a981-02752e40f1bf.png)

I do not use any event brokers.

### Command / Request

```shell
After upgrade from Rasa 3.2.5 to 3.2.6 this bug start to appear.

`pip install rasa --upgrade
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\Ronny\miniconda3\envs\RASA_env\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Ronny\miniconda3\envs\RASA_env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ronny\miniconda3\envs\RASA_env\Scripts\rasa.exe\__main__.py", line 4, in <module>
  File "C:\Users\Ronny\miniconda3\envs\RASA_env\lib\site-packages\rasa\__main__.py", line 14, in <module>
    from rasa.cli import (
  File "C:\Users\Ronny\miniconda3\envs\RASA_env\lib\site-packages\rasa\cli\export.py", line 16, in <module>
    from rasa.core.brokers.pika import PikaEventBroker
  File "C:\Users\Ronny\miniconda3\envs\RASA_env\lib\site-packages\rasa\core\brokers\pika.py", line 27, in <module>
    class PikaEventBroker(EventBroker):
  File "C:\Users\Ronny\miniconda3\envs\RASA_env\lib\site-packages\rasa\core\brokers\pika.py", line 161, in PikaEventBroker
    async def _connect(self) -> aio_pika.abc.AbstractRobustConnection:
AttributeError: module 'aio_pika' has no attribute 'abc'
```

**Comment by kozlice** [comment]
Try `pip install --upgrade aio-pika`. This dependency has been updated in #11434
