### PR TITLE
Rasa x startup issues with Rasa Open Source 2.2.x and Rasa X < 0.35

### LINKED ISSUE #7592: After upgrade rasa from v2.1.3 to v2.2.1, local rasa x server doesn't work
**Rasa version**: 2.2.1

**Rasa SDK version** (if used & relevant): 2.2.0

**Rasa X version** (if used & relevant): 0.34.0

**Python version**: 3.8.6

**Operating system** (windows, osx, ...): macOS Big Sur version 11.1

**Issue**:
After upgrade rasa from v2.1.3 to v2.2.1, local rasa x server doesn't work.
Only after I edited `rasa cli` source code, it did work.
```
# rasa/cli/x.py
# line 493 ~ 499
local.main(
            args,
            project_path,
            args.data,
            token=rasa_x_token,
            config_path=config_path
            # domain_path=domain_path # I removed it!
        )
```

**Error (including full traceback)**:
```
(venv) (base) ➜  rasa git:(feature/prototype) ✗ rasa x
Traceback (most recent call last):
  File "/Users/ys/dev/rasa/venv/lib/python3.8/site-packages/rasa/cli/x.py", line 493, in run_locally
    local.main(
TypeError: main() got an unexpected keyword argument 'domain_path'

Sorry, something went wrong (see error above). Make sure to start Rasa X with valid data and valid domain and config files. Please, also check any warnings that popped up.
If you need help fixing the issue visit our forum: https://forum.rasa.com/.
(venv) (base) ➜  rasa git:(feature/prototype) ✗ rasa x --v
Traceback (most recent call last):
  File "/Users/ys/dev/rasa/venv/lib/python3.8/site-packages/rasa/cli/x.py", line 493, in run_locally
    local.main(
TypeError: main() got an unexpected keyword argument 'domain_path'

Sorry, something went wrong (see error above). Make sure to start Rasa X with valid data and valid domain and config files. Please, also check any warnings that popped up.
If you need help fixing the issue visit our forum: https://forum.rasa.com/.
```

**Command or request that led to error**:
```
rasa x
```

### PR DESCRIPTION
**Pull request by tmbo**
**Proposed changes**:
- fixes #7592 

**Status (please check what you already did)**:
- [x] updated the documentation
- [x] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
- [x] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)

### CODE REVIEW

**Review by mprazz — APPROVED** [review]
Amazing, thanks for the quick fix! 😊

**Review by tczekajlo — APPROVED** [review]

**Comment by giladpn** [comment]
Excuse me I hope this is the right place for this comment. The proposed fix to the `domain_path` issue is indeed relevant but then the issue "moves to another place" and there is a problem with an invalid handle (probably when starting the Rasa X event server), at least on Windows with Python 3.8.5.

Please see the detailed tracebacks and version info on https://github.com/RasaHQ/rasa/issues/7592#issuecomment-752730559

Thank you and apologies if this is not the right place to raise this
